### ISSUE TITLE
Open Wiki And FAQs!!

### ISSUE THREAD

**Issue by Percivius** [shubhayshah/Calculator#2]
Hi... I was wondering you could add FAQs in the codedCalculator project!!!

Thank you!!

**Comment by shubhayshah** [comment]
Absolutely, @TechnoXtremeDevZ ! I will include this in the 0.4 Version... and perhaps a Wiki by the 0.16 version...

**Comment by Percivius** [comment]
Thank you, @shubhayshah ! I will close this now... keep up the GOOD WORK!!!
